
export const staticCss = {
  recipes: {
    button: [
      { intent: ['*'], appearance: ['*'] },
      { shape: ['*'] },
      { size: ['*'] },
      { glow: ['*'] },
      { isGrow: ['*'] },
    ],
    iconButton: [{ intent: ['*'], appearance: ['*'] }, { shape: ['*'] }, { size: ['*'] }],
    directionalButton: [
      { intent: ['*'], appearance: ['*'] },
      { shape: ['*'] },
      { size: ['*'] },
      { orientation: ['*'] },
      { connected: ['*'] },
      { direction: ['*'] },
    ],
    toggleButton: [
      { intent: ['*'] },
      { variant: ['*'] },
      { shape: ['*'] },
      { size: ['*'] },
      { pressed: ['*'] },
    ],
    splitButton: [
      { intent: ['*'] },
      { variant: ['*'] },
      { shape: ['*'] },
      { size: ['*'] },
      { isOpen: ['*'] },
    ],
    dividerStyle: [{ orientation: ['*'] }, { variant: ['*'] }],
    stackStyle: [
      { direction: ['*'] },
      { align: ['*'] },
      { justify: ['*'] },
      { gap: ['*'] },
      { wrap: ['*'] },
      { motion: ['*'] },
    ],
    flexStyle: [
      { direction: ['*'] },
      { align: ['*'] },
      { justify: ['*'] },
      { gap: ['*'] },
      { wrap: ['*'] },
    ],
    gridStyle: [{ ratio: ['*'] }, { gap: ['*'] }],
    simpleGrid: [{ columns: ['*'] }, { gap: ['*'] }],
    text: [{ variant: ['*'] }, { weight: ['*'] }, { align: ['*'] }, { transform: ['*'] }],
    heading: [{ level: ['*'] }, { weight: ['*'] }],
    link: [{ variant: ['*'] }, { colorScheme: ['*'] }],
    kbd: [{ size: ['*'] }, { overflow: ['*'] }],
    blockquote: [{ tone: ['*'] }],
    badge: [
      { intent: ['*'], appearance: ['*'] },
      { size: ['*'] },
      { placement: ['*'] },
      { shape: ['*'] },
    ],
    icon: [{ size: ['*'] }, { variant: ['*'] }, { disabled: ['*'] }],
    alert: [{ status: ['*'] }, { variant: ['*'] }, { closable: ['*'] }],
    circleProgress: [
      { variant: ['primary', 'secondary', 'info', 'success', 'warning', 'danger'] },
      { appearance: ['*'] },
      { animation: ['*'] },
    ],
    spinner: [{ variant: ['*'], animation: ['*'], conditions: ['motionSubtle', 'motionPop'] }],
    puff: [{ intent: ['*'] }, { appearance: ['*'] }, { point: ['*'] }, { size: ['*'] }],
    progressBar: [
      { intent: ['primary', 'secondary', 'info', 'success', 'warning', 'danger', 'light', 'dark'] },
      { appearance: ['*'] },
      { shape: ['*'] },
      { pattern: ['*'] },
      { animationType: ['*'] },
      { borderType: ['*'] },
      { labelPosition: ['*'] },
    ],
    result: [{ status: ['*'] }, { appearance: ['*'] }],
    card: [{ appearance: ['*'] }, { intent: ['*'] }, { shape: ['*'] }],
    tag: [{ size: ['*'] }, { appearance: ['*'] }, { intent: ['*'] }, { shape: ['*'] }],
    closeButton: [{ size: ['*'] }, { appearance: ['*'] }, { shape: ['*'] }],
    buttonGroup: [
      { orientation: ['*'] },
      { spacing: ['*'] },
      { connected: ['*'] },
      { fullWidth: ['*'] },
    ],
    avatar: [{ size: ['*'] }, { shape: ['*'] }],
    avatarGroup: [{ size: ['*'] }, { spacing: ['*'] }],
    skeleton: [{ variant: ['*'] }, { shape: ['*'] }, { animation: ['*'] }],
    stat: [{ size: ['*'] }, { type: ['*'] }, { intent: ['*'] }],
    image: [{ sizing: ['*'] }, { fit: ['*'] }, { aspectRatio: ['*'] }, { radius: ['*'] }],
    picture: [{ sizing: ['*'] }, { fit: ['*'] }],
    emptyState: [{ size: ['*'] }, { appearance: ['*'] }, { intent: ['*'] }],
    breadcrumbs: [{ size: ['*'] }, { variant: ['*'] }],
    list: [{ variant: ['*'] }],
    table: [
      { variant: ['*'] },
      { layout: ['*'] },
      { stickyHeader: ['*'] },
      { headerTone: ['*'] },
      { size: ['*'] },
    ],
    reference: [{ appearance: ['*'] }, { size: ['*'] }, { overflow: ['*'] }],
    diffViewer: [{ mode: ['*'] }, { size: ['*'] }],
    code: [{ variant: ['*'] }, { colorScheme: ['*'] }],
    codeViewer: [{ size: ['*'] }, { wrap: ['*'] }],
    keyValueViewer: [{ size: ['*'] }, { columns: ['*'] }],
    markdownViewer: [{ size: ['*'] }],
    input: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    textarea: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    select: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    comboBox: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    multiSelect: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    numberInput: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    inputGroup: [{ size: ['*'] }],
    otpInput: [{ appearance: ['*'] }, { size: ['*'] }],
    fileUploader: [{ appearance: ['*'] }, { intent: ['*'] }],
    switchControl: [{ size: ['*'] }, { intent: ['*'] }],
    checkbox: [{ size: ['*'] }, { intent: ['*'] }, { error: ['*'] }],
    radioGroup: [{ orientation: ['*'] }],
    radio: [{ size: ['*'] }, { intent: ['*'] }, { error: ['*'] }],
    rangeSlider: [{ size: ['*'] }, { intent: ['*'] }, { error: ['*'] }],
    slider: [{ size: ['*'] }, { intent: ['*'] }],
    listboxSelect: [{ variant: ['*'] }, { size: ['*'] }, { error: ['*'] }],
    wheelPicker: [{ size: ['*'] }, { error: ['*'] }],
    calendar: [{ size: ['*'] }],
    timePicker: [{ size: ['*'] }],
    timeClock: [{ size: ['*'] }],
    commandMenu: [{ size: ['*'] }],
    navbar: [{ appearance: ['*'] }, { sticky: ['*'] }, { narrowLayout: ['*'] }, { justify: ['*'] }],
    pagination: [{ appearance: ['*'] }, { size: ['*'] }],
    sidebar: [{ appearance: ['*'] }, { collapsed: ['*'] }],
    stepper: [{ appearance: ['*'] }, { intent: ['*'] }, { orientation: ['*'] }, { size: ['*'] }],
    tabs: [{ size: ['*'] }, { variant: ['*'] }, { orientation: ['*'] }],
    scrollArea: [{ size: ['*'] }],
    dropdown: [{ appearance: ['*'] }, { size: ['*'] }],
    tooltip: [{ theme: ['*'] }],
    drawer: [{ appearance: ['*'] }, { placement: ['*'] }, { size: ['*'] }],
    hoverCard: [{ appearance: ['*'] }, { size: ['*'] }],
    modal: [{ appearance: ['*'] }, { size: ['*'] }, { scrollBehavior: ['*'] }],
    alertDialog: [
      { appearance: ['*'] },
      { intent: ['*'] },
      { size: ['*'] },
      { scrollBehavior: ['*'] },
    ],
    accordion: [{ appearance: ['*'] }],
    collapsible: [{ appearance: ['*'] }],
    treeView: [{ appearance: ['*'] }],
  },
};
