import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/activation/index.ts',
    'src/hooks/index.ts',
    'src/accordion/index.ts',
    'src/calendar/index.ts',
    'src/clipboard/index.ts',
    'src/combobox/index.ts',
    'src/command-menu/index.ts',
    'src/collapsible/index.ts',
    'src/context-menu/index.ts',
    'src/date/index.ts',
    'src/date/react/index.ts',
    'src/datetime/index.ts',
    'src/dropdown/index.ts',
    'src/file-upload/index.ts',
    'src/file-upload/react/index.ts',
    'src/json/index.ts',
    'src/listbox/index.ts',
    'src/listbox/react/index.ts',
    'src/markdown/index.ts',
    'src/multi-select/index.ts',
    'src/number-input/index.ts',
    'src/otp-input/index.ts',
    'src/otp-input/react/index.ts',
    'src/pagination/index.ts',
    'src/radio-group/index.ts',
    'src/range-slider/index.ts',
    'src/range-slider/react/index.ts',
    'src/scroll-area/index.ts',
    'src/screen-composer/index.ts',
    'src/split-button/index.ts',
    'src/time/index.ts',
    'src/toggle-button/index.ts',
    'src/tree-view/index.ts',
    'src/wheel-picker/index.ts',
    'src/wheel-picker/react/index.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
});
